model:
  name: unsloth/llama-3-vision-11b-bnb
  use_flash_attention: true
  load_in_4bit: true
  device_map: auto
  trust_remote_code: true

tokenizer:
  padding_side: right
  truncation: true
  max_length: 512

generation:
  max_new_tokens: 200
  temperature: 0.7
  top_p: 0.9
  do_sample: true
  use_cache: true
  num_beams: 1
  early_stopping: true
